#numpy


In [6]:
import numpy
numpy.__version__
import numpy as np


In [10]:
result = 0
for i in range(100):
    result += i

print(result)

4950


In [23]:
l=list(range(10))
print(l)
print(type(l[0]))
print(type(l))

l2=list(str(c) for c in l )
print(l2)
print(type(l2[0]))
print(type(l2))

l3=[True,"c",2,3.4]
[type(item) for item in l3]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'int'>
<class 'list'>
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'str'>
<class 'list'>


[bool, str, int, float]

In [5]:
import array
L=list(range(10))
print(L)
A=array.array("i",L)
A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [8]:
import numpy as np
np.array([2.4,8,9,23])
# NumPy arrays can only contain data of the same type


array([ 2.4,  8. ,  9. , 23. ])

In [13]:
import numpy as np
np.array([5,8,9], dtype=np.float32)

array([5., 8., 9.], dtype=float32)

In [15]:
np.array([3,8.9,12], dtype=int)

array([ 3,  8, 12])

In [17]:
np.array([3,14,17,"s"])

array(['3', '14', '17', 's'], dtype='<U11')

In [20]:
# np.array([12,3,"s"],dtype=int)

##error

In [24]:
for i in range(10):
    print(0, end=" ")



0 0 0 0 0 0 0 0 0 0 

In [41]:
number=list(range(10))
print(number)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [43]:
zeros=[0]*10
print(zeros)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [44]:
np.zeros(10, dtype=int)
# Create a length-10 integer array filled with 0s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])